spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://210.122.3.31:3306/new_center?serverTimezone=UTC&characterEncoding=EUC-KR&zeroDateTimeBehavior=convertToNull
    username: root
    password: devdbsuper2015!@#
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://210.122.3.31:3306/new_center?serverTimezone=UTC&characterEncoding=EUC-KR&zeroDateTimeBehavior=convertToNull
#    username: rlvdms
#    password: todrkr122
  devtools:
    add-properties: false

logging:
  dir: ./logs

jwt:
  header: Authorization
  secret: "fjilawjeflasj!@#42314sdafj234!@#2313"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dailystudy.dtmsapi.dto
